import {v4 as uuid} from 'uuid';

export const LOGIN = uuid();
console.log(LOGIN, 'LOGIN');
export const DASHBOARD = uuid();
console.log(DASHBOARD, 'DASHBOARD');
export const RESET = uuid();
console.log(RESET, 'RESET');
export const SIGNUP = uuid();
console.log(SIGNUP, 'SIGNUP');
export const OPERATIONS = uuid();
console.log(OPERATIONS, 'OPERATIONS');
export const SOLAR = uuid();
console.log(SOLAR, 'SOLAR');
export const STORAGE = uuid();
console.log(STORAGE, 'STORAGE');
export const GENERATOR = uuid();
console.log(GENERATOR, 'GENERATOR');
export const FORECAST = uuid();
console.log(FORECAST, 'FORECAST');